[tool.black]
target-version = ["py37"]
line-length = 88
include = '\.py$'
skip-string-normalization = true
exclude = '''
/(
    \.git
  | \.venv
)/
'''

[tool.isort]
profile = "black"

[tool.mypy]
python_version = 3.7
disallow_untyped_calls = true
disallow_untyped_defs = true